name: Auto Commit

on:
  schedule:
    # 6:00 AM IST
    - cron: '30 0 * * *'

    # 1:00 PM IST
    - cron: '30 7 * * *'

    # 11:30 PM IST
    - cron: '0 18 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "Rahul Mondal"
          git config --global user.email "postbox9635@gmail.com"

      - name: Update Commit Counter
        run: |
          if [ ! -f commit_state.txt ]; then
            echo "0" > commit_state.txt
          fi

          COUNT=$(cat commit_state.txt)
          COUNT=$((COUNT + 1))
          echo "$COUNT" > commit_state.txt

          echo "Random Commit #$COUNT at $(date -u)" >> commits.txt

      - name: Commit & Push
        run: |
          git add commit_state.txt commits.txt

          git commit -m "🤖 Random Commit #$(cat commit_state.txt)" || exit 0

          git push
